### ISSUE TITLE
Migrations documentation

### ISSUE THREAD

**Issue by michalhosna** [contember/docs#5]
There should be documentation for all modifications.

Especially because documentation explicitly tell users to review the file, 
but there is no real way one could review and understand the file at the moment
https://github.com/contember/doc/blob/4439af0690a0faf57d9456fed50f30f96ee95321/docs/schema/migrations.md#L23

**Comment by jonasNobile** [comment]
Thanks @michalhosna for this issue. We have changed our documentation accordingly:

There is documentation for manually fixing or writing migration. Documentation does not tell users to review migration file any more.
